const NON_GROUP_MAX_TIMES_USED = 4;
const GROUP_MAX_TIMES_USED = 7;

const TRAINING_QUESTIONS_AMOUNT = 2;
const TEST_NON_GROUP_QUESTIONS_AMOUNT = 18;

const BONUS_MULTIPLIER = 0.1;

export {
  NON_GROUP_MAX_TIMES_USED,
  GROUP_MAX_TIMES_USED,
  TRAINING_QUESTIONS_AMOUNT,
  TEST_NON_GROUP_QUESTIONS_AMOUNT,
  BONUS_MULTIPLIER
};
