const TIME_PER_QUESTION = 60000 * 6;

const TRAINING_MIN_ANSWERS = 2;

const BONUS_MULTIPLIER = 0.1;

const GAME_ALERT_ROUND = 18;

export { TRAINING_MIN_ANSWERS, TIME_PER_QUESTION, GAME_ALERT_ROUND, BONUS_MULTIPLIER };
