const TIME_PER_QUESTION = 60000 * 6;

const TRAINING_QUESTIONS = 1;
const TRAINING_MIN_ANSWERS = 2;

const GAME_QUESTIONS = 25;

export { GAME_QUESTIONS, TRAINING_QUESTIONS, TRAINING_MIN_ANSWERS, TIME_PER_QUESTION };
